# Generated by Django 4.0 on 2022-02-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workconnect', '0002_formregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormRegistration',
            new_name='ClientRegistration',
        ),
    ]
