# Generated by Django 4.0 on 2022-02-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workconnect', '0003_rename_formregistration_clientregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregistration',
            name='Description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='Email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='JOB',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='Location',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='Type',
            field=models.TextField(max_length=70),
        ),
    ]
