# Generated by Django 4.0 on 2022-02-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workconnect', '0004_alter_clientregistration_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.TextField(max_length=20)),
                ('Last_name', models.TextField(max_length=200)),
                ('Company_Name', models.TextField(max_length=100)),
                ('Chamber_of_Commerce_number', models.TextField(max_length=70)),
                ('Intriduction', models.TextField(max_length=70)),
                ('Work_experience', models.TextField(max_length=70)),
                ('Summary', models.TextField(max_length=70)),
                ('Education', models.TextField(max_length=70)),
                ('pics', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
