# Generated by Django 4.0.1 on 2022-02-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workconnect', '0007_rename_email_post_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregistration',
            name='Description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='Email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='JOB',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='Location',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='Type',
            field=models.TextField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='clientregistration',
            name='pics',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
