# Generated by Django 4.0.1 on 2022-02-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workconnect', '0008_alter_clientregistration_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='businessclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('name', models.TextField(max_length=200)),
                ('contect', models.TextField(max_length=100)),
                ('tellphone', models.IntegerField(max_length=70)),
                ('stad', models.TextField(max_length=70)),
                ('straat', models.TextField(max_length=70)),
                ('postcode', models.TextField(max_length=70)),
                ('website', models.URLField(max_length=70)),
                ('KVK', models.TextField(max_length=200)),
            ],
        ),
    ]
