# Generated by Django 4.0.1 on 2022-02-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workconnect', '0009_businessclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='link',
            field=models.URLField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='lonk',
            field=models.URLField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='mail',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='tellphone',
            field=models.IntegerField(),
        ),
    ]
