# Generated by Django 4.0.1 on 2022-02-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('distance', models.TextField(blank=True, choices=[('8KM', '8KM'), ('3KM', '3KM'), ('5KM', '5KM'), ('4KM', '4KM'), ('6KM', '6KM'), ('9KM', '9KM'), ('7KM', '7KM')], max_length=40, null=True)),
                ('Categories', models.TextField(choices=[('Marketing and Communication', 'Marketing and Communication'), ('Healthcare & Pharmaceuticals', 'Healthcare & Pharmaceuticals'), ('Architecture & Design', 'Architecture & Design'), ('Facility management', 'Facility management'), ('Banks', 'Banks'), ('Engineering', 'Engineering'), ('Chemistry, Oil & Energy', 'Chemistry, Oil & Energy'), ('Security', 'Security'), ('Media and Journalism', 'Media and Journalism'), ('Trade, Wholesale and Retail', 'Trade, Wholesale and Retail'), ('Defence', 'Defence'), ('General', 'General'), ('Build', 'Build'), ('Catering industry', 'Catering industry'), ('Finance', 'Finance'), ('Research', 'Research'), ('Agricultural & Environmental', 'Agricultural & Environmental'), ('Travel and Recreation', 'Travel and Recreation'), ('Aviation and Maritime', 'Aviation and Maritime'), ('Law enforcement', 'Law enforcement'), ('Art and Culture and Entrainment', 'Art and Culture and Entrainment'), ('Government and Semi-Government', 'Government and Semi-Government'), ('9KM', 'Township'), ('Employment agencies and Recruitment and Selection', 'Employment agencies and Recruitment and Selection'), ('Betting & Gaming', 'Betting & Gaming'), ('Technic', 'Technic'), ('Life sciences', 'Life sciences'), ('Automotive', 'Automotive'), ('Real Estate and Brokerage', 'Real Estate and Brokerage'), ('Education', 'Education'), ('Legal', 'Legal'), ('Animals & Care', 'Animals & Care'), ('Nutrition and Exercise', 'Nutrition and Exercise'), ('IT', 'IT'), ('Business services', 'Business services'), ('Fashion & Styling', 'Fashion & Styling'), ('Transport and Logistics', 'Transport and Logistics'), ('Industry and Production', 'Industry and Production')], max_length=4000)),
                ('till_date', models.DateTimeField()),
                ('remark', models.CharField(max_length=50000)),
                ('address', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
