# Generated by Django 4.0.1 on 2022-02-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advrt',
            name='Categories',
            field=models.TextField(choices=[('Healthcare & Pharmaceuticals', 'Healthcare & Pharmaceuticals'), ('Facility management', 'Facility management'), ('Aviation and Maritime', 'Aviation and Maritime'), ('Marketing and Communication', 'Marketing and Communication'), ('IT', 'IT'), ('Employment agencies and Recruitment and Selection', 'Employment agencies and Recruitment and Selection'), ('Nutrition and Exercise', 'Nutrition and Exercise'), ('Legal', 'Legal'), ('Travel and Recreation', 'Travel and Recreation'), ('Chemistry, Oil & Energy', 'Chemistry, Oil & Energy'), ('Architecture & Design', 'Architecture & Design'), ('Fashion & Styling', 'Fashion & Styling'), ('Technic', 'Technic'), ('Life sciences', 'Life sciences'), ('Defence', 'Defence'), ('Government and Semi-Government', 'Government and Semi-Government'), ('Media and Journalism', 'Media and Journalism'), ('Banks', 'Banks'), ('Security', 'Security'), ('Industry and Production', 'Industry and Production'), ('Engineering', 'Engineering'), ('Research', 'Research'), ('Agricultural & Environmental', 'Agricultural & Environmental'), ('Build', 'Build'), ('9KM', 'Township'), ('Education', 'Education'), ('Finance', 'Finance'), ('Law enforcement', 'Law enforcement'), ('Business services', 'Business services'), ('Real Estate and Brokerage', 'Real Estate and Brokerage'), ('Transport and Logistics', 'Transport and Logistics'), ('Animals & Care', 'Animals & Care'), ('Trade, Wholesale and Retail', 'Trade, Wholesale and Retail'), ('General', 'General'), ('Catering industry', 'Catering industry'), ('Art and Culture and Entrainment', 'Art and Culture and Entrainment'), ('Betting & Gaming', 'Betting & Gaming'), ('Automotive', 'Automotive')], max_length=4000),
        ),
        migrations.AlterField(
            model_name='advrt',
            name='distance',
            field=models.TextField(blank=True, choices=[('6KM', '6KM'), ('3KM', '3KM'), ('5KM', '5KM'), ('7KM', '7KM'), ('8KM', '8KM'), ('4KM', '4KM'), ('9KM', '9KM')], max_length=40, null=True),
        ),
    ]
