# Generated by Django 4.0.1 on 2022-02-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advrt_categories_alter_advrt_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advrt',
            name='Categories',
            field=models.TextField(choices=[('Government and Semi-Government', 'Government and Semi-Government'), ('Catering industry', 'Catering industry'), ('9KM', 'Township'), ('Architecture & Design', 'Architecture & Design'), ('Nutrition and Exercise', 'Nutrition and Exercise'), ('Chemistry, Oil & Energy', 'Chemistry, Oil & Energy'), ('Industry and Production', 'Industry and Production'), ('Real Estate and Brokerage', 'Real Estate and Brokerage'), ('Business services', 'Business services'), ('General', 'General'), ('Build', 'Build'), ('Healthcare & Pharmaceuticals', 'Healthcare & Pharmaceuticals'), ('Security', 'Security'), ('Trade, Wholesale and Retail', 'Trade, Wholesale and Retail'), ('Law enforcement', 'Law enforcement'), ('Research', 'Research'), ('Employment agencies and Recruitment and Selection', 'Employment agencies and Recruitment and Selection'), ('Engineering', 'Engineering'), ('Automotive', 'Automotive'), ('Defence', 'Defence'), ('Aviation and Maritime', 'Aviation and Maritime'), ('Finance', 'Finance'), ('Marketing and Communication', 'Marketing and Communication'), ('Life sciences', 'Life sciences'), ('Fashion & Styling', 'Fashion & Styling'), ('Education', 'Education'), ('IT', 'IT'), ('Agricultural & Environmental', 'Agricultural & Environmental'), ('Betting & Gaming', 'Betting & Gaming'), ('Legal', 'Legal'), ('Media and Journalism', 'Media and Journalism'), ('Animals & Care', 'Animals & Care'), ('Facility management', 'Facility management'), ('Travel and Recreation', 'Travel and Recreation'), ('Transport and Logistics', 'Transport and Logistics'), ('Technic', 'Technic'), ('Art and Culture and Entrainment', 'Art and Culture and Entrainment'), ('Banks', 'Banks')], max_length=4000),
        ),
        migrations.AlterField(
            model_name='advrt',
            name='distance',
            field=models.TextField(blank=True, choices=[('9KM', '9KM'), ('3KM', '3KM'), ('5KM', '5KM'), ('6KM', '6KM'), ('4KM', '4KM'), ('7KM', '7KM'), ('8KM', '8KM')], max_length=40, null=True),
        ),
    ]
